// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: pkg/pb/job/jobseeker/job.proto

package jobseeker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobSeekerGetAppliedJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *JobSeekerGetAppliedJobsRequest) Reset() {
	*x = JobSeekerGetAppliedJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerGetAppliedJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerGetAppliedJobsRequest) ProtoMessage() {}

func (x *JobSeekerGetAppliedJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerGetAppliedJobsRequest.ProtoReflect.Descriptor instead.
func (*JobSeekerGetAppliedJobsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_job_jobseeker_job_proto_rawDescGZIP(), []int{0}
}

func (x *JobSeekerGetAppliedJobsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type JobSeekerGetAppliedJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jobs []*AppliedJobs `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
}

func (x *JobSeekerGetAppliedJobsResponse) Reset() {
	*x = JobSeekerGetAppliedJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerGetAppliedJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerGetAppliedJobsResponse) ProtoMessage() {}

func (x *JobSeekerGetAppliedJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerGetAppliedJobsResponse.ProtoReflect.Descriptor instead.
func (*JobSeekerGetAppliedJobsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_job_jobseeker_job_proto_rawDescGZIP(), []int{1}
}

func (x *JobSeekerGetAppliedJobsResponse) GetJobs() []*AppliedJobs {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type AppliedJobs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId       int64  `protobuf:"varint,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	UserId      int64  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	RecruiterId int64  `protobuf:"varint,4,opt,name=recruiterId,proto3" json:"recruiterId,omitempty"`
	Status      string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CoverLetter string `protobuf:"bytes,6,opt,name=coverLetter,proto3" json:"coverLetter,omitempty"`
	ResumeUrl   string `protobuf:"bytes,7,opt,name=resumeUrl,proto3" json:"resumeUrl,omitempty"`
}

func (x *AppliedJobs) Reset() {
	*x = AppliedJobs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppliedJobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppliedJobs) ProtoMessage() {}

func (x *AppliedJobs) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppliedJobs.ProtoReflect.Descriptor instead.
func (*AppliedJobs) Descriptor() ([]byte, []int) {
	return file_pkg_pb_job_jobseeker_job_proto_rawDescGZIP(), []int{2}
}

func (x *AppliedJobs) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppliedJobs) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *AppliedJobs) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AppliedJobs) GetRecruiterId() int64 {
	if x != nil {
		return x.RecruiterId
	}
	return 0
}

func (x *AppliedJobs) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AppliedJobs) GetCoverLetter() string {
	if x != nil {
		return x.CoverLetter
	}
	return ""
}

func (x *AppliedJobs) GetResumeUrl() string {
	if x != nil {
		return x.ResumeUrl
	}
	return ""
}

type JobSeekerGetAllJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *JobSeekerGetAllJobsRequest) Reset() {
	*x = JobSeekerGetAllJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerGetAllJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerGetAllJobsRequest) ProtoMessage() {}

func (x *JobSeekerGetAllJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerGetAllJobsRequest.ProtoReflect.Descriptor instead.
func (*JobSeekerGetAllJobsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_job_jobseeker_job_proto_rawDescGZIP(), []int{3}
}

func (x *JobSeekerGetAllJobsRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type JobSeekerGetAllJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jobs []*JSGetAllJobsRespons `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
}

func (x *JobSeekerGetAllJobsResponse) Reset() {
	*x = JobSeekerGetAllJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerGetAllJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerGetAllJobsResponse) ProtoMessage() {}

func (x *JobSeekerGetAllJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerGetAllJobsResponse.ProtoReflect.Descriptor instead.
func (*JobSeekerGetAllJobsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_job_jobseeker_job_proto_rawDescGZIP(), []int{4}
}

func (x *JobSeekerGetAllJobsResponse) GetJobs() []*JSGetAllJobsRespons {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type JSGetAllJobsRespons struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *JSGetAllJobsRespons) Reset() {
	*x = JSGetAllJobsRespons{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSGetAllJobsRespons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSGetAllJobsRespons) ProtoMessage() {}

func (x *JSGetAllJobsRespons) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSGetAllJobsRespons.ProtoReflect.Descriptor instead.
func (*JSGetAllJobsRespons) Descriptor() ([]byte, []int) {
	return file_pkg_pb_job_jobseeker_job_proto_rawDescGZIP(), []int{5}
}

func (x *JSGetAllJobsRespons) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JSGetAllJobsRespons) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type JobSeekerGetJobByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *JobSeekerGetJobByIDRequest) Reset() {
	*x = JobSeekerGetJobByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerGetJobByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerGetJobByIDRequest) ProtoMessage() {}

func (x *JobSeekerGetJobByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerGetJobByIDRequest.ProtoReflect.Descriptor instead.
func (*JobSeekerGetJobByIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_job_jobseeker_job_proto_rawDescGZIP(), []int{6}
}

func (x *JobSeekerGetJobByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type JobSeekerGetJobByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Job *Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
}

func (x *JobSeekerGetJobByIDResponse) Reset() {
	*x = JobSeekerGetJobByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerGetJobByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerGetJobByIDResponse) ProtoMessage() {}

func (x *JobSeekerGetJobByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerGetJobByIDResponse.ProtoReflect.Descriptor instead.
func (*JobSeekerGetJobByIDResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_job_jobseeker_job_proto_rawDescGZIP(), []int{7}
}

func (x *JobSeekerGetJobByIDResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type JobSeekerApplyJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId       uint64 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	UserId      uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CoverLetter string `protobuf:"bytes,3,opt,name=cover_letter,json=coverLetter,proto3" json:"cover_letter,omitempty"`
	Resume      []byte `protobuf:"bytes,4,opt,name=resume,proto3" json:"resume,omitempty"`
}

func (x *JobSeekerApplyJobRequest) Reset() {
	*x = JobSeekerApplyJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerApplyJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerApplyJobRequest) ProtoMessage() {}

func (x *JobSeekerApplyJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerApplyJobRequest.ProtoReflect.Descriptor instead.
func (*JobSeekerApplyJobRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_job_jobseeker_job_proto_rawDescGZIP(), []int{8}
}

func (x *JobSeekerApplyJobRequest) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *JobSeekerApplyJobRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *JobSeekerApplyJobRequest) GetCoverLetter() string {
	if x != nil {
		return x.CoverLetter
	}
	return ""
}

func (x *JobSeekerApplyJobRequest) GetResume() []byte {
	if x != nil {
		return x.Resume
	}
	return nil
}

type JobSeekerApplyJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Job *AppliedJobs `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
}

func (x *JobSeekerApplyJobResponse) Reset() {
	*x = JobSeekerApplyJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerApplyJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerApplyJobResponse) ProtoMessage() {}

func (x *JobSeekerApplyJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerApplyJobResponse.ProtoReflect.Descriptor instead.
func (*JobSeekerApplyJobResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_job_jobseeker_job_proto_rawDescGZIP(), []int{9}
}

func (x *JobSeekerApplyJobResponse) GetJob() *AppliedJobs {
	if x != nil {
		return x.Job
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title               string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location            string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	EmployerId          int64                  `protobuf:"varint,5,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	EmploymentType      string                 `protobuf:"bytes,6,opt,name=employment_type,json=employmentType,proto3" json:"employment_type,omitempty"`
	Salary              int64                  `protobuf:"varint,7,opt,name=salary,proto3" json:"salary,omitempty"`
	SkillsRequired      string                 `protobuf:"bytes,8,opt,name=skills_required,json=skillsRequired,proto3" json:"skills_required,omitempty"`
	ExperienceLevel     string                 `protobuf:"bytes,9,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"`
	EducationLevel      string                 `protobuf:"bytes,10,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	ApplicationDeadline *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=application_deadline,json=applicationDeadline,proto3" json:"application_deadline,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_job_jobseeker_job_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_pkg_pb_job_jobseeker_job_proto_rawDescGZIP(), []int{10}
}

func (x *Job) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Job) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Job) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Job) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Job) GetEmployerId() int64 {
	if x != nil {
		return x.EmployerId
	}
	return 0
}

func (x *Job) GetEmploymentType() string {
	if x != nil {
		return x.EmploymentType
	}
	return ""
}

func (x *Job) GetSalary() int64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *Job) GetSkillsRequired() string {
	if x != nil {
		return x.SkillsRequired
	}
	return ""
}

func (x *Job) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

func (x *Job) GetEducationLevel() string {
	if x != nil {
		return x.EducationLevel
	}
	return ""
}

func (x *Job) GetApplicationDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.ApplicationDeadline
	}
	return nil
}

var File_pkg_pb_job_jobseeker_job_proto protoreflect.FileDescriptor

var file_pkg_pb_job_jobseeker_job_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6a, 0x6f, 0x62, 0x2f, 0x6a, 0x6f, 0x62,
	0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2f, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x6a, 0x6f, 0x62, 0x5f, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x39, 0x0a, 0x1e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x1f, 0x4a,
	0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x65, 0x64, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e,
	0x0a, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6a,
	0x6f, 0x62, 0x5f, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2e, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x22, 0xc5,
	0x01, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6a,
	0x6f, 0x62, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x4c,
	0x65, 0x74, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x32, 0x0a, 0x1a, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65,
	0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x55, 0x0a, 0x1b, 0x4a, 0x6f,
	0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x6a, 0x6f, 0x62,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6a, 0x6f,
	0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x53, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x52, 0x04, 0x6a, 0x6f, 0x62,
	0x73, 0x22, 0x3b, 0x0a, 0x13, 0x4a, 0x53, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x2c,
	0x0a, 0x1a, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4a, 0x6f,
	0x62, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x1b,
	0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x42,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x03, 0x6a,
	0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6a,
	0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x03, 0x6a, 0x6f,
	0x62, 0x22, 0x85, 0x01, 0x0a, 0x18, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x41,
	0x70, 0x70, 0x6c, 0x79, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15,
	0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x4c, 0x65, 0x74, 0x74, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x19, 0x4a, 0x6f, 0x62,
	0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65,
	0x6b, 0x65, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x73, 0x52,
	0x03, 0x6a, 0x6f, 0x62, 0x22, 0x97, 0x03, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61,
	0x6c, 0x61, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x61, 0x6c, 0x61,
	0x72, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x5f, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x65,
	0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63,
	0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x4d, 0x0a, 0x14, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64,
	0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x13, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x32, 0xcb,
	0x03, 0x0a, 0x0c, 0x4a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x12,
	0x6e, 0x0a, 0x13, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x29, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6a, 0x6f, 0x62,
	0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2a, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65,
	0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x6e, 0x0a, 0x13, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4a,
	0x6f, 0x62, 0x42, 0x79, 0x49, 0x44, 0x12, 0x29, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6a, 0x6f, 0x62,
	0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72,
	0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2a, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65,
	0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4a, 0x6f,
	0x62, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x68, 0x0a, 0x11, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x4a, 0x6f, 0x62, 0x12, 0x27, 0x2e, 0x6a, 0x6f, 0x62, 0x5f, 0x6a, 0x6f, 0x62, 0x73, 0x65,
	0x65, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x41, 0x70,
	0x70, 0x6c, 0x79, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x6a, 0x6f, 0x62, 0x5f, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f,
	0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x71, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x2d, 0x2e, 0x6a, 0x6f,
	0x62, 0x5f, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x53,
	0x65, 0x65, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x4a,
	0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x6a, 0x6f, 0x62,
	0x5f, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x65,
	0x65, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x4a, 0x6f,
	0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x18, 0x5a, 0x16,
	0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6a, 0x6f, 0x62, 0x2f, 0x6a, 0x6f, 0x62,
	0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_job_jobseeker_job_proto_rawDescOnce sync.Once
	file_pkg_pb_job_jobseeker_job_proto_rawDescData = file_pkg_pb_job_jobseeker_job_proto_rawDesc
)

func file_pkg_pb_job_jobseeker_job_proto_rawDescGZIP() []byte {
	file_pkg_pb_job_jobseeker_job_proto_rawDescOnce.Do(func() {
		file_pkg_pb_job_jobseeker_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_job_jobseeker_job_proto_rawDescData)
	})
	return file_pkg_pb_job_jobseeker_job_proto_rawDescData
}

var file_pkg_pb_job_jobseeker_job_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_pb_job_jobseeker_job_proto_goTypes = []interface{}{
	(*JobSeekerGetAppliedJobsRequest)(nil),  // 0: job_jobseeker.JobSeekerGetAppliedJobsRequest
	(*JobSeekerGetAppliedJobsResponse)(nil), // 1: job_jobseeker.JobSeekerGetAppliedJobsResponse
	(*AppliedJobs)(nil),                     // 2: job_jobseeker.AppliedJobs
	(*JobSeekerGetAllJobsRequest)(nil),      // 3: job_jobseeker.JobSeekerGetAllJobsRequest
	(*JobSeekerGetAllJobsResponse)(nil),     // 4: job_jobseeker.JobSeekerGetAllJobsResponse
	(*JSGetAllJobsRespons)(nil),             // 5: job_jobseeker.JSGetAllJobsRespons
	(*JobSeekerGetJobByIDRequest)(nil),      // 6: job_jobseeker.JobSeekerGetJobByIDRequest
	(*JobSeekerGetJobByIDResponse)(nil),     // 7: job_jobseeker.JobSeekerGetJobByIDResponse
	(*JobSeekerApplyJobRequest)(nil),        // 8: job_jobseeker.JobSeekerApplyJobRequest
	(*JobSeekerApplyJobResponse)(nil),       // 9: job_jobseeker.JobSeekerApplyJobResponse
	(*Job)(nil),                             // 10: job_jobseeker.Job
	(*timestamppb.Timestamp)(nil),           // 11: google.protobuf.Timestamp
}
var file_pkg_pb_job_jobseeker_job_proto_depIdxs = []int32{
	2,  // 0: job_jobseeker.JobSeekerGetAppliedJobsResponse.jobs:type_name -> job_jobseeker.AppliedJobs
	5,  // 1: job_jobseeker.JobSeekerGetAllJobsResponse.jobs:type_name -> job_jobseeker.JSGetAllJobsRespons
	10, // 2: job_jobseeker.JobSeekerGetJobByIDResponse.job:type_name -> job_jobseeker.Job
	2,  // 3: job_jobseeker.JobSeekerApplyJobResponse.job:type_name -> job_jobseeker.AppliedJobs
	11, // 4: job_jobseeker.Job.application_deadline:type_name -> google.protobuf.Timestamp
	3,  // 5: job_jobseeker.JobseekerJob.JobSeekerGetAllJobs:input_type -> job_jobseeker.JobSeekerGetAllJobsRequest
	6,  // 6: job_jobseeker.JobseekerJob.JobSeekerGetJobByID:input_type -> job_jobseeker.JobSeekerGetJobByIDRequest
	8,  // 7: job_jobseeker.JobseekerJob.JobSeekerApplyJob:input_type -> job_jobseeker.JobSeekerApplyJobRequest
	0,  // 8: job_jobseeker.JobseekerJob.GetAppliedJobs:input_type -> job_jobseeker.JobSeekerGetAppliedJobsRequest
	4,  // 9: job_jobseeker.JobseekerJob.JobSeekerGetAllJobs:output_type -> job_jobseeker.JobSeekerGetAllJobsResponse
	7,  // 10: job_jobseeker.JobseekerJob.JobSeekerGetJobByID:output_type -> job_jobseeker.JobSeekerGetJobByIDResponse
	9,  // 11: job_jobseeker.JobseekerJob.JobSeekerApplyJob:output_type -> job_jobseeker.JobSeekerApplyJobResponse
	1,  // 12: job_jobseeker.JobseekerJob.GetAppliedJobs:output_type -> job_jobseeker.JobSeekerGetAppliedJobsResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_pb_job_jobseeker_job_proto_init() }
func file_pkg_pb_job_jobseeker_job_proto_init() {
	if File_pkg_pb_job_jobseeker_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_job_jobseeker_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerGetAppliedJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_job_jobseeker_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerGetAppliedJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_job_jobseeker_job_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppliedJobs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_job_jobseeker_job_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerGetAllJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_job_jobseeker_job_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerGetAllJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_job_jobseeker_job_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSGetAllJobsRespons); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_job_jobseeker_job_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerGetJobByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_job_jobseeker_job_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerGetJobByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_job_jobseeker_job_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerApplyJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_job_jobseeker_job_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerApplyJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_job_jobseeker_job_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_job_jobseeker_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_job_jobseeker_job_proto_goTypes,
		DependencyIndexes: file_pkg_pb_job_jobseeker_job_proto_depIdxs,
		MessageInfos:      file_pkg_pb_job_jobseeker_job_proto_msgTypes,
	}.Build()
	File_pkg_pb_job_jobseeker_job_proto = out.File
	file_pkg_pb_job_jobseeker_job_proto_rawDesc = nil
	file_pkg_pb_job_jobseeker_job_proto_goTypes = nil
	file_pkg_pb_job_jobseeker_job_proto_depIdxs = nil
}
