// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: pkg/pb/job/jobseeker/job.proto

package jobseeker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	JobseekerJob_JobSeekerGetAllJobs_FullMethodName = "/job.JobseekerJob/JobSeekerGetAllJobs"
	JobseekerJob_JobSeekerGetJobByID_FullMethodName = "/job.JobseekerJob/JobSeekerGetJobByID"
	JobseekerJob_JobSeekerApplyJob_FullMethodName   = "/job.JobseekerJob/JobSeekerApplyJob"
	JobseekerJob_GetAppliedJobs_FullMethodName      = "/job.JobseekerJob/GetAppliedJobs"
)

// JobseekerJobClient is the client API for JobseekerJob service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobseekerJobClient interface {
	JobSeekerGetAllJobs(ctx context.Context, in *JobSeekerGetAllJobsRequest, opts ...grpc.CallOption) (*JobSeekerGetAllJobsResponse, error)
	JobSeekerGetJobByID(ctx context.Context, in *JobSeekerGetJobByIDRequest, opts ...grpc.CallOption) (*JobSeekerGetJobByIDResponse, error)
	JobSeekerApplyJob(ctx context.Context, in *JobSeekerApplyJobRequest, opts ...grpc.CallOption) (*JobSeekerApplyJobResponse, error)
	GetAppliedJobs(ctx context.Context, in *JobSeekerGetAppliedJobsRequest, opts ...grpc.CallOption) (*JobSeekerGetAppliedJobsResponse, error)
}

type jobseekerJobClient struct {
	cc grpc.ClientConnInterface
}

func NewJobseekerJobClient(cc grpc.ClientConnInterface) JobseekerJobClient {
	return &jobseekerJobClient{cc}
}

func (c *jobseekerJobClient) JobSeekerGetAllJobs(ctx context.Context, in *JobSeekerGetAllJobsRequest, opts ...grpc.CallOption) (*JobSeekerGetAllJobsResponse, error) {
	out := new(JobSeekerGetAllJobsResponse)
	err := c.cc.Invoke(ctx, JobseekerJob_JobSeekerGetAllJobs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobseekerJobClient) JobSeekerGetJobByID(ctx context.Context, in *JobSeekerGetJobByIDRequest, opts ...grpc.CallOption) (*JobSeekerGetJobByIDResponse, error) {
	out := new(JobSeekerGetJobByIDResponse)
	err := c.cc.Invoke(ctx, JobseekerJob_JobSeekerGetJobByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobseekerJobClient) JobSeekerApplyJob(ctx context.Context, in *JobSeekerApplyJobRequest, opts ...grpc.CallOption) (*JobSeekerApplyJobResponse, error) {
	out := new(JobSeekerApplyJobResponse)
	err := c.cc.Invoke(ctx, JobseekerJob_JobSeekerApplyJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobseekerJobClient) GetAppliedJobs(ctx context.Context, in *JobSeekerGetAppliedJobsRequest, opts ...grpc.CallOption) (*JobSeekerGetAppliedJobsResponse, error) {
	out := new(JobSeekerGetAppliedJobsResponse)
	err := c.cc.Invoke(ctx, JobseekerJob_GetAppliedJobs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobseekerJobServer is the server API for JobseekerJob service.
// All implementations must embed UnimplementedJobseekerJobServer
// for forward compatibility
type JobseekerJobServer interface {
	JobSeekerGetAllJobs(context.Context, *JobSeekerGetAllJobsRequest) (*JobSeekerGetAllJobsResponse, error)
	JobSeekerGetJobByID(context.Context, *JobSeekerGetJobByIDRequest) (*JobSeekerGetJobByIDResponse, error)
	JobSeekerApplyJob(context.Context, *JobSeekerApplyJobRequest) (*JobSeekerApplyJobResponse, error)
	GetAppliedJobs(context.Context, *JobSeekerGetAppliedJobsRequest) (*JobSeekerGetAppliedJobsResponse, error)
	mustEmbedUnimplementedJobseekerJobServer()
}

// UnimplementedJobseekerJobServer must be embedded to have forward compatible implementations.
type UnimplementedJobseekerJobServer struct {
}

func (UnimplementedJobseekerJobServer) JobSeekerGetAllJobs(context.Context, *JobSeekerGetAllJobsRequest) (*JobSeekerGetAllJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobSeekerGetAllJobs not implemented")
}
func (UnimplementedJobseekerJobServer) JobSeekerGetJobByID(context.Context, *JobSeekerGetJobByIDRequest) (*JobSeekerGetJobByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobSeekerGetJobByID not implemented")
}
func (UnimplementedJobseekerJobServer) JobSeekerApplyJob(context.Context, *JobSeekerApplyJobRequest) (*JobSeekerApplyJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobSeekerApplyJob not implemented")
}
func (UnimplementedJobseekerJobServer) GetAppliedJobs(context.Context, *JobSeekerGetAppliedJobsRequest) (*JobSeekerGetAppliedJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppliedJobs not implemented")
}
func (UnimplementedJobseekerJobServer) mustEmbedUnimplementedJobseekerJobServer() {}

// UnsafeJobseekerJobServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobseekerJobServer will
// result in compilation errors.
type UnsafeJobseekerJobServer interface {
	mustEmbedUnimplementedJobseekerJobServer()
}

func RegisterJobseekerJobServer(s grpc.ServiceRegistrar, srv JobseekerJobServer) {
	s.RegisterService(&JobseekerJob_ServiceDesc, srv)
}

func _JobseekerJob_JobSeekerGetAllJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobSeekerGetAllJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobseekerJobServer).JobSeekerGetAllJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobseekerJob_JobSeekerGetAllJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobseekerJobServer).JobSeekerGetAllJobs(ctx, req.(*JobSeekerGetAllJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobseekerJob_JobSeekerGetJobByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobSeekerGetJobByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobseekerJobServer).JobSeekerGetJobByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobseekerJob_JobSeekerGetJobByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobseekerJobServer).JobSeekerGetJobByID(ctx, req.(*JobSeekerGetJobByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobseekerJob_JobSeekerApplyJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobSeekerApplyJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobseekerJobServer).JobSeekerApplyJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobseekerJob_JobSeekerApplyJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobseekerJobServer).JobSeekerApplyJob(ctx, req.(*JobSeekerApplyJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobseekerJob_GetAppliedJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobSeekerGetAppliedJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobseekerJobServer).GetAppliedJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobseekerJob_GetAppliedJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobseekerJobServer).GetAppliedJobs(ctx, req.(*JobSeekerGetAppliedJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobseekerJob_ServiceDesc is the grpc.ServiceDesc for JobseekerJob service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobseekerJob_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "job.JobseekerJob",
	HandlerType: (*JobseekerJobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JobSeekerGetAllJobs",
			Handler:    _JobseekerJob_JobSeekerGetAllJobs_Handler,
		},
		{
			MethodName: "JobSeekerGetJobByID",
			Handler:    _JobseekerJob_JobSeekerGetJobByID_Handler,
		},
		{
			MethodName: "JobSeekerApplyJob",
			Handler:    _JobseekerJob_JobSeekerApplyJob_Handler,
		},
		{
			MethodName: "GetAppliedJobs",
			Handler:    _JobseekerJob_GetAppliedJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/job/jobseeker/job.proto",
}
