apiVersion: apps/v1
kind: Deployment
metadata:
  name: connecthub-api-gateway
  namespace: connecthub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api_gateway
  template:
    metadata:
     labels:
       app: api_gateway
    spec:
      containers:
        - name: api-gateway-container
          image: aruncm7/connecthub-api-gateway
          ports:
            - containerPort: 7000
          resources:
            limits:
              memory: 212Mi
              cpu: ".2"
            requests:
              memory: 150Mi
              cpu: "0.1"



---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: connecthub
spec:
  type: LoadBalancer
  ports:
    - targetPort: 7000
      port: 7000
      nodePort: 30003
  selector: 
    app: api_gateway