apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: connecthub-certificate
  namespace: connecthub
spec:
  dnsNames:
    - connecthub.ardev.online
  secretName: connecthub-new-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer