// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: pkg/pb/auth/jobseeker/jobseeker.proto

package jobseeker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobSeekerSignupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email           string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password        string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string `protobuf:"bytes,3,opt,name=confirmPassword,proto3" json:"confirmPassword,omitempty"`
	Firstname       string `protobuf:"bytes,4,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname        string `protobuf:"bytes,5,opt,name=lastname,proto3" json:"lastname,omitempty"`
	PhoneNumber     string `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	DateOfBirth     string `protobuf:"bytes,7,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender          string `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
}

func (x *JobSeekerSignupRequest) Reset() {
	*x = JobSeekerSignupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerSignupRequest) ProtoMessage() {}

func (x *JobSeekerSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerSignupRequest.ProtoReflect.Descriptor instead.
func (*JobSeekerSignupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{0}
}

func (x *JobSeekerSignupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *JobSeekerSignupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *JobSeekerSignupRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

func (x *JobSeekerSignupRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *JobSeekerSignupRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *JobSeekerSignupRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *JobSeekerSignupRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *JobSeekerSignupRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type JobSeekerSignupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status           int64             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	JobSeekerDetails *JobSeekerDetails `protobuf:"bytes,2,opt,name=JobSeekerDetails,proto3" json:"JobSeekerDetails,omitempty"`
	Token            string            `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Error            string            `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *JobSeekerSignupResponse) Reset() {
	*x = JobSeekerSignupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerSignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerSignupResponse) ProtoMessage() {}

func (x *JobSeekerSignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerSignupResponse.ProtoReflect.Descriptor instead.
func (*JobSeekerSignupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{1}
}

func (x *JobSeekerSignupResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *JobSeekerSignupResponse) GetJobSeekerDetails() *JobSeekerDetails {
	if x != nil {
		return x.JobSeekerDetails
	}
	return nil
}

func (x *JobSeekerSignupResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JobSeekerSignupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type JobSeekerDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email       string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Firstname   string `protobuf:"bytes,3,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname    string `protobuf:"bytes,4,opt,name=lastname,proto3" json:"lastname,omitempty"`
	PhoneNumber string `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	DateOfBirth string `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender      string `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
}

func (x *JobSeekerDetails) Reset() {
	*x = JobSeekerDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerDetails) ProtoMessage() {}

func (x *JobSeekerDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerDetails.ProtoReflect.Descriptor instead.
func (*JobSeekerDetails) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{2}
}

func (x *JobSeekerDetails) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JobSeekerDetails) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *JobSeekerDetails) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *JobSeekerDetails) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *JobSeekerDetails) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *JobSeekerDetails) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *JobSeekerDetails) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type JobSeekerLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *JobSeekerLoginRequest) Reset() {
	*x = JobSeekerLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerLoginRequest) ProtoMessage() {}

func (x *JobSeekerLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerLoginRequest.ProtoReflect.Descriptor instead.
func (*JobSeekerLoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{3}
}

func (x *JobSeekerLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *JobSeekerLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type JobSeekerLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status           int64             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	JobSeekerDetails *JobSeekerDetails `protobuf:"bytes,2,opt,name=JobSeekerDetails,proto3" json:"JobSeekerDetails,omitempty"`
	Token            string            `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Error            string            `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *JobSeekerLoginResponse) Reset() {
	*x = JobSeekerLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerLoginResponse) ProtoMessage() {}

func (x *JobSeekerLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerLoginResponse.ProtoReflect.Descriptor instead.
func (*JobSeekerLoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{4}
}

func (x *JobSeekerLoginResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *JobSeekerLoginResponse) GetJobSeekerDetails() *JobSeekerDetails {
	if x != nil {
		return x.JobSeekerDetails
	}
	return nil
}

func (x *JobSeekerLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JobSeekerLoginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username    string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email       string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Website     string `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	Location    string `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Phone       string `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Bio         string `protobuf:"bytes,8,opt,name=bio,proto3" json:"bio,omitempty"`
	DateOfBirth string `protobuf:"bytes,9,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender      string `protobuf:"bytes,10,opt,name=gender,proto3" json:"gender,omitempty"`
}

func (x *AddProfileRequest) Reset() {
	*x = AddProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProfileRequest) ProtoMessage() {}

func (x *AddProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProfileRequest.ProtoReflect.Descriptor instead.
func (*AddProfileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{5}
}

func (x *AddProfileRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddProfileRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *AddProfileRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AddProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AddProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *AddProfileRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *AddProfileRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type AddProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddProfileResponse) Reset() {
	*x = AddProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProfileResponse) ProtoMessage() {}

func (x *AddProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProfileResponse.ProtoReflect.Descriptor instead.
func (*AddProfileResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{6}
}

func (x *AddProfileResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddProfileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{7}
}

func (x *GetProfileRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int64             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Profile *JobSeekerProfile `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfileResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetProfileResponse) GetProfile() *JobSeekerProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type JobSeekerProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName   string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Gender      string `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Email       string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	DateOfBirth string `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Phone       string `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	LastName    string `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
}

func (x *JobSeekerProfile) Reset() {
	*x = JobSeekerProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerProfile) ProtoMessage() {}

func (x *JobSeekerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerProfile.ProtoReflect.Descriptor instead.
func (*JobSeekerProfile) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{9}
}

func (x *JobSeekerProfile) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JobSeekerProfile) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *JobSeekerProfile) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *JobSeekerProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *JobSeekerProfile) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *JobSeekerProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *JobSeekerProfile) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type JobSeekerEditProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile *JobSeekerProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *JobSeekerEditProfileRequest) Reset() {
	*x = JobSeekerEditProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerEditProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerEditProfileRequest) ProtoMessage() {}

func (x *JobSeekerEditProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerEditProfileRequest.ProtoReflect.Descriptor instead.
func (*JobSeekerEditProfileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{10}
}

func (x *JobSeekerEditProfileRequest) GetProfile() *JobSeekerProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type JobSeekerEditProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile *JobSeekerProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *JobSeekerEditProfileResponse) Reset() {
	*x = JobSeekerEditProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerEditProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerEditProfileResponse) ProtoMessage() {}

func (x *JobSeekerEditProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerEditProfileResponse.ProtoReflect.Descriptor instead.
func (*JobSeekerEditProfileResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{11}
}

func (x *JobSeekerEditProfileResponse) GetProfile() *JobSeekerProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type JobSeekerOTPLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *JobSeekerOTPLoginRequest) Reset() {
	*x = JobSeekerOTPLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerOTPLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerOTPLoginRequest) ProtoMessage() {}

func (x *JobSeekerOTPLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerOTPLoginRequest.ProtoReflect.Descriptor instead.
func (*JobSeekerOTPLoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{12}
}

func (x *JobSeekerOTPLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type JobSeekerOTPLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Otp    string `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *JobSeekerOTPLoginResponse) Reset() {
	*x = JobSeekerOTPLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerOTPLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerOTPLoginResponse) ProtoMessage() {}

func (x *JobSeekerOTPLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerOTPLoginResponse.ProtoReflect.Descriptor instead.
func (*JobSeekerOTPLoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{13}
}

func (x *JobSeekerOTPLoginResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *JobSeekerOTPLoginResponse) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *JobSeekerOTPLoginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OtpVerificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Otp   string `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
}

func (x *OtpVerificationRequest) Reset() {
	*x = OtpVerificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OtpVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpVerificationRequest) ProtoMessage() {}

func (x *OtpVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpVerificationRequest.ProtoReflect.Descriptor instead.
func (*OtpVerificationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{14}
}

func (x *OtpVerificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OtpVerificationRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type OtpVerificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Verified bool   `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
	Error    string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *OtpVerificationResponse) Reset() {
	*x = OtpVerificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OtpVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpVerificationResponse) ProtoMessage() {}

func (x *OtpVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpVerificationResponse.ProtoReflect.Descriptor instead.
func (*OtpVerificationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{15}
}

func (x *OtpVerificationResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OtpVerificationResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *OtpVerificationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPassword string `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword string `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	RePassword  string `protobuf:"bytes,4,opt,name=re_password,json=rePassword,proto3" json:"re_password,omitempty"`
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{16}
}

func (x *ChangePasswordRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetRePassword() string {
	if x != nil {
		return x.RePassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP(), []int{17}
}

func (x *ChangePasswordResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ChangePasswordResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_pb_auth_jobseeker_jobseeker_proto protoreflect.FileDescriptor

var file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x6a, 0x6f,
	0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2f, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b,
	0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x22, 0x8d, 0x02, 0x0a, 0x16, 0x4a, 0x6f, 0x62, 0x53, 0x65,
	0x65, 0x6b, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0d, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x6f, 0x66, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0xaa, 0x01, 0x0a, 0x17, 0x4a, 0x6f, 0x62, 0x53, 0x65,
	0x65, 0x6b, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x4b, 0x0a, 0x10, 0x4a, 0x6f,
	0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x10, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0xd1, 0x01, 0x0a, 0x10, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c,
	0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0d, 0x64,
	0x61, 0x74, 0x65, 0x5f, 0x6f, 0x66, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x49, 0x0a, 0x15, 0x4a, 0x6f, 0x62, 0x53, 0x65,
	0x65, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0xa9, 0x01, 0x0a, 0x16, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x4b, 0x0a, 0x10, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b,
	0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x10, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x83,
	0x02, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65,
	0x62, 0x73, 0x69, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x65, 0x62,
	0x73, 0x69, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x6f, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x6f, 0x12, 0x22, 0x0a, 0x0d, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x6f, 0x66, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x22, 0x42, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x67, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x07, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6a,
	0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4a, 0x6f, 0x62,
	0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0xc6, 0x01, 0x0a, 0x10, 0x4a, 0x6f, 0x62, 0x53, 0x65,
	0x65, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x22, 0x0a, 0x0d, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x6f, 0x66, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x58, 0x0a, 0x1b, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x45, 0x64, 0x69, 0x74,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x59, 0x0a, 0x1c, 0x4a, 0x6f, 0x62,
	0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x45, 0x64, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x07, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6a, 0x6f, 0x62,
	0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x65,
	0x65, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x22, 0x30, 0x0a, 0x18, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65,
	0x72, 0x4f, 0x54, 0x50, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x5b, 0x0a, 0x19, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65,
	0x6b, 0x65, 0x72, 0x4f, 0x54, 0x50, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6f,
	0x74, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x74, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x40, 0x0a, 0x16, 0x4f, 0x74, 0x70, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x74, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6f, 0x74, 0x70, 0x22, 0x63, 0x0a, 0x17, 0x4f, 0x74, 0x70, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x97, 0x01, 0x0a, 0x15, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x6f, 0x6c, 0x64, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x6c, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0x46, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x99, 0x06, 0x0a,
	0x09, 0x4a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x12, 0x62, 0x0a, 0x0f, 0x4a, 0x6f,
	0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x25, 0x2e,
	0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4a, 0x6f,
	0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x53, 0x69,
	0x67, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f,
	0x0a, 0x0e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x24, 0x2e, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b,
	0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x51, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x20, 0x2e,
	0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x64,
	0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5a, 0x0a, 0x13, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x20, 0x2e, 0x6a, 0x6f, 0x62, 0x73,
	0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6a, 0x6f,
	0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f,
	0x0a, 0x14, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x45, 0x64, 0x69, 0x74, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x2a, 0x2e, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b,
	0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72,
	0x45, 0x64, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x45, 0x64, 0x69, 0x74,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x66, 0x0a, 0x11, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x4f, 0x54, 0x50, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x27, 0x2e, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x4f, 0x54,
	0x50, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4a, 0x6f,
	0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x4f, 0x54, 0x50, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x0f, 0x4f, 0x74, 0x70, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x2e, 0x6a, 0x6f, 0x62,
	0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4f, 0x74, 0x70, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x26, 0x2e, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x4f, 0x74, 0x70, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x0e, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x24, 0x2e, 0x6a, 0x6f,
	0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65,
	0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescOnce sync.Once
	file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescData = file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDesc
)

func file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescGZIP() []byte {
	file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescOnce.Do(func() {
		file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescData)
	})
	return file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDescData
}

var file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pkg_pb_auth_jobseeker_jobseeker_proto_goTypes = []interface{}{
	(*JobSeekerSignupRequest)(nil),       // 0: jobseekerauth.JobSeekerSignupRequest
	(*JobSeekerSignupResponse)(nil),      // 1: jobseekerauth.JobSeekerSignupResponse
	(*JobSeekerDetails)(nil),             // 2: jobseekerauth.JobSeekerDetails
	(*JobSeekerLoginRequest)(nil),        // 3: jobseekerauth.JobSeekerLoginRequest
	(*JobSeekerLoginResponse)(nil),       // 4: jobseekerauth.JobSeekerLoginResponse
	(*AddProfileRequest)(nil),            // 5: jobseekerauth.AddProfileRequest
	(*AddProfileResponse)(nil),           // 6: jobseekerauth.AddProfileResponse
	(*GetProfileRequest)(nil),            // 7: jobseekerauth.GetProfileRequest
	(*GetProfileResponse)(nil),           // 8: jobseekerauth.GetProfileResponse
	(*JobSeekerProfile)(nil),             // 9: jobseekerauth.JobSeekerProfile
	(*JobSeekerEditProfileRequest)(nil),  // 10: jobseekerauth.JobSeekerEditProfileRequest
	(*JobSeekerEditProfileResponse)(nil), // 11: jobseekerauth.JobSeekerEditProfileResponse
	(*JobSeekerOTPLoginRequest)(nil),     // 12: jobseekerauth.JobSeekerOTPLoginRequest
	(*JobSeekerOTPLoginResponse)(nil),    // 13: jobseekerauth.JobSeekerOTPLoginResponse
	(*OtpVerificationRequest)(nil),       // 14: jobseekerauth.OtpVerificationRequest
	(*OtpVerificationResponse)(nil),      // 15: jobseekerauth.OtpVerificationResponse
	(*ChangePasswordRequest)(nil),        // 16: jobseekerauth.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),       // 17: jobseekerauth.ChangePasswordResponse
}
var file_pkg_pb_auth_jobseeker_jobseeker_proto_depIdxs = []int32{
	2,  // 0: jobseekerauth.JobSeekerSignupResponse.JobSeekerDetails:type_name -> jobseekerauth.JobSeekerDetails
	2,  // 1: jobseekerauth.JobSeekerLoginResponse.JobSeekerDetails:type_name -> jobseekerauth.JobSeekerDetails
	9,  // 2: jobseekerauth.GetProfileResponse.profile:type_name -> jobseekerauth.JobSeekerProfile
	9,  // 3: jobseekerauth.JobSeekerEditProfileRequest.profile:type_name -> jobseekerauth.JobSeekerProfile
	9,  // 4: jobseekerauth.JobSeekerEditProfileResponse.profile:type_name -> jobseekerauth.JobSeekerProfile
	0,  // 5: jobseekerauth.Jobseeker.JobSeekerSignup:input_type -> jobseekerauth.JobSeekerSignupRequest
	3,  // 6: jobseekerauth.Jobseeker.JobSeekerLogin:input_type -> jobseekerauth.JobSeekerLoginRequest
	5,  // 7: jobseekerauth.Jobseeker.AddProfile:input_type -> jobseekerauth.AddProfileRequest
	7,  // 8: jobseekerauth.Jobseeker.JobSeekerGetProfile:input_type -> jobseekerauth.GetProfileRequest
	10, // 9: jobseekerauth.Jobseeker.JobSeekerEditProfile:input_type -> jobseekerauth.JobSeekerEditProfileRequest
	12, // 10: jobseekerauth.Jobseeker.JobSeekerOTPLogin:input_type -> jobseekerauth.JobSeekerOTPLoginRequest
	14, // 11: jobseekerauth.Jobseeker.OtpVerification:input_type -> jobseekerauth.OtpVerificationRequest
	16, // 12: jobseekerauth.Jobseeker.ChangePassword:input_type -> jobseekerauth.ChangePasswordRequest
	1,  // 13: jobseekerauth.Jobseeker.JobSeekerSignup:output_type -> jobseekerauth.JobSeekerSignupResponse
	4,  // 14: jobseekerauth.Jobseeker.JobSeekerLogin:output_type -> jobseekerauth.JobSeekerLoginResponse
	6,  // 15: jobseekerauth.Jobseeker.AddProfile:output_type -> jobseekerauth.AddProfileResponse
	8,  // 16: jobseekerauth.Jobseeker.JobSeekerGetProfile:output_type -> jobseekerauth.GetProfileResponse
	11, // 17: jobseekerauth.Jobseeker.JobSeekerEditProfile:output_type -> jobseekerauth.JobSeekerEditProfileResponse
	13, // 18: jobseekerauth.Jobseeker.JobSeekerOTPLogin:output_type -> jobseekerauth.JobSeekerOTPLoginResponse
	15, // 19: jobseekerauth.Jobseeker.OtpVerification:output_type -> jobseekerauth.OtpVerificationResponse
	17, // 20: jobseekerauth.Jobseeker.ChangePassword:output_type -> jobseekerauth.ChangePasswordResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_pb_auth_jobseeker_jobseeker_proto_init() }
func file_pkg_pb_auth_jobseeker_jobseeker_proto_init() {
	if File_pkg_pb_auth_jobseeker_jobseeker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerSignupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerSignupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerEditProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerEditProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerOTPLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerOTPLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OtpVerificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OtpVerificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangePasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangePasswordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_auth_jobseeker_jobseeker_proto_goTypes,
		DependencyIndexes: file_pkg_pb_auth_jobseeker_jobseeker_proto_depIdxs,
		MessageInfos:      file_pkg_pb_auth_jobseeker_jobseeker_proto_msgTypes,
	}.Build()
	File_pkg_pb_auth_jobseeker_jobseeker_proto = out.File
	file_pkg_pb_auth_jobseeker_jobseeker_proto_rawDesc = nil
	file_pkg_pb_auth_jobseeker_jobseeker_proto_goTypes = nil
	file_pkg_pb_auth_jobseeker_jobseeker_proto_depIdxs = nil
}
